version: "3.7"

services:
  mylab:
    container_name: "svr1"
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    ports:
      - "1401:1433"
